apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaosbox-mysql
  name: chaosbox-mysql
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: chaosbox-mysql
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaosbox
  name: chaosbox
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: chaosbox
  sessionAffinity: None
  type: ClusterIP
